namespace :db do
  desc "Remaking data"
  task remake_data: :environment do

    puts "Reset"
    Rake::Task["db:migrate:reset"].invoke
    ADDRESSES = [
      "39 Đào Tấn, P Ngọc Khánh, Q Ba Đình",
      "62 Yên Phụ, P Yên Phụ, Q Tây Hồ",
      " 133 Tây Sơn, Đống Đa",
      "148 Trần Duy Hưng, P Trung Hòa, Q Cầu Giấy",
      " Tòa nhà RESCO - 521 Kim Mã, P Ngọc Khánh, Q Ba Đình",
      "Thị trấn Đông Anh, H. Đông Anh",
      "765 Nguyễn Văn Linh, Q. Long Biên",
      "Thị trấn Trâu Quỳ, H. Gia Lâm",
      "Thị trấn Đông Anh, H. Đông Anh",
      "KCN Dương Xá, Gia Lâm",
      "105A Khương Thượng, Đống Đa",
      " E6 Quỳnh Mai, Hai Bà Trưng",
      "Ngô Gia Tự, Long Biên",
      "Chương Dương PGD Kim Ngưu",
      "Chương Dương Tissue Sông Đuống",
      "Chương Dương Tổng Cty May 10",
      "Chương Dương Trung tâm Thương mại Savico",
      "Đông Anh Trụ sở VCB",
      "Hà Nội 29 Hàng Phèn",
      "Hà Nội Autobank Hàng Lược",
      "Hà Nội Bộ giáo dục đào tạo",
      "Hà Nội Bộ NN&PTNT",
      "Hà Nội Công ty Katolec",
      "Hà Nội KCN Nội Bài",
      "Hà Nội Khách sạn Fortuna",
      "Hà Nội Khách Sạn Melia ",
      "Hà Nội Kho bạc Nhà Nước Hà Nội",
      "SỐ 36 HOÀNG CẦU ĐỐNG ĐA HÀ NỘI 8H-17H",
      "NGUYỄN HỮU THỌ ĐẠI KIM HOÀNG MAI  24/24",
      "51 Lạc Trung, P Vĩnh Tuy, Q Hai Bà Trưng  24/24",
      "Hoàng Mai, Hà Nội 8h-17h",
      "72 Nguyễn Du, Hai Bà Trưng  08h-17h00",
      "Hàng Bài, P Hàng Bài, Q Hoàn Kiếm  8h-21h",
      "Quang Trung, P Trần Hưng Đạo, Q Hoàn Kiếm 24/24",
      "Lò Sũ, P Lý Thái Tổ, Q Hoàn Kiếm  8h-16h",
      "36 Hoàng Cầu, P Ô Chợ Dừa, Q Đống Đa  24/24",
      "5 Đường Nguyễn Hữu Thọ - Bắc Linh Đàm, P Đại Kim, Q Hoàng Mai   24/24; 8h-17h",
      "Số 434 Trần Khát Chân, P Phố Huế, Q Hai Bà Trưng  8h-16h",
      "2 211 Trung Kính, Cầu Giấy  24/24",
      "Số 1 Đào Duy Anh-Đống Đa-Hà Nội 24/24",
      "78 Nguyễn Du, P. Nguyễn Du, Q. Hai Bà Trưng 8h - 22h",
      "11B Cát Linh  24/24",
      "344 Bà Triệu, P Lê Đại Hành, Q Hai Bà Trưng 24/24",
      "SỐ 8 CỔ LINH LONG BIÊN HÀ NỘI 9H-22H30",
      "484 Quang Trung, P La Khê, Q Hà Đông  5h-24h",
      "10 Quang Trung, P Quang Trung, Hà Đông  24/24",
      "Lô CN2- Khu đô thị Định Công, Q Hoàng Mai 24/24",
      "150D Lò Đúc, P.Phạm Đình Hổ, Q.Hai Bà Trưng 7h30-21h",
      "106 Nguyễn An Ninh, Q Hoàng Mai 24/24",
      "23 Phan Chu Trinh, P. Phan Chu Chinh, Q. Hoàn Kiếm  24/24",
      "Tầng 1, Tower 1, Times City, số 458 Minh Khai, P Vĩnh Tuy, Q Hai Bà Trưng 24/24",
      "1277 Giải Phóng, P Thịnh Liệt, Q Hoàng Mai  6h-22h",
      "DUONG NGUYEN HUU CANH AP.XOM HO X.PHU HOI H.NT DN 6-22h",
      "Thôn Đông Phước , Xã Hòa An, Huyên Tuy Hòa, Tỉnh Phú Yên  24/24",
      "94 Quốc Lộ 9 - Đông Hà  24/24",
      "1174 Đường Láng, P Láng Thượng, Q Đống Đa 24/24",
      "14 Thụy Khuê, P Thụy Khuê, Q Tây Hồ Nội bộ",
      "20 Lê Trọng Tấn, P Khương Trung, Q Thanh Xuân 7h30-17h",
      "22 Ngô Quyền, P Tràng Tiền, Q Hoàn Kiếm 24/24",
      "229 Hoàng Hoa Thám, P Ngọc Hà, Q Ba Đình  24/24",
      "252 Kim Mã, P Kim Mã, Q Ba Đình 24/24",
      "260 Nguyễn Văn Cừ, P Bồ Đề, Q Long Biên 24/24",
      "27 Lạc Trung, P. Vĩnh Tuy, Hai Bà Trưng 24/24",
      "29 Nguyễn Chí Thanh, P Ngọc Khánh, Q Ba Đình  24/24",
      "299 Cầu Giấy, P Dịch Vọng, Q Cầu Giấy 24/24",
      "3 Đặng Thái Thân, P Phan Chu Trinh, Q Hoàn Kiếm 24/24",
      "36 Lý Thái Tổ, P Lý Thái Tổ, Q Hoàn Kiếm  24/24",
      "69 Vũ Ngọc Phan, P Láng Hạ, Q Đống Đa 24/24",
      "84 Ngọc Hà, P Đội Cấn, Q Ba Đình  24/24",
      "9 Đường Thanh Niên, P Quán Thánh, Q Ba Đình 24/24",
      "95 Đường Láng, P Ngã Tư Sở, Q Đống Đa 7h30-17h",
      "7 Phan Đình Phùng, P Quán Thánh, Q Ba Đình  24/24",
      "1 Phương Mai, P Phương Mai, Q Thanh Xuân  24/24",
      "Số 1 Trần Khánh Dư, Q Hai Bà Trưng  Nội bộ",
      "10 Chu Văn An, P Điện Biên, Q Ba Đình 24/24",
      "28 Trần Hưng Đạo, P Phan Chu Trinh, Q Hoàn Kiếm Nội bộ",
      "1194 Đường Láng, P. Láng Thượng, Q. Đống Đa Nội bộ",
      "KCN Bắc Thăng Long  24/24",
      "50B Châu Long, P Trúc Bạch, Q Ba Đình 24/24",
      "49 Hàng Bài, P Hàng Bài, Q Hoàn Kiếm  24/24",
      "499 Nguyễn Trãi, P Thanh Xuân Trung, Q Thanh Xuân 24/24",
      "KCN Bắc Thăng Long, Đông Anh  24/24",
      "336 Nguyễn Trãi, P Thanh Xuân Trung, Q Thanh Xuân 24/24",
      "91 Chùa Láng, P Láng Thượng, Q Đống Đa  24/24 (nội bộ)",
      "175 Tây Sơn, P Trung Liệt, Q Đống Đa  24/24 (nội bộ)",
      "77 Nguyễn Chí Thanh, Láng Hạ, Đống Đa 24/24",
      "198 Trần Quang Khải, P Lý Thái Tổ, Q Hoàn Kiếm  24/24",
      "KCN Bắc Thăng Long, Xã Võng La, Huyện Đông Anh  24/24",
      "KCN Sài Đồng, P Sài Đồng, Q Long Biên 24/24",
      "KCN Từ Liêm, H Từ Liêm  24/24",
      "110 Cầu Giấy, P Quan Hoa, Q Cầu Giấy  24/24",
      "110 Thái Thịnh, P Trung Liệt, Q Đống Đa 24/24",
      "44 Lý Thường Kiệt, Hai Bà Trưng Nội bộ",
      "25 Trần Nhân Tông, P Trần Nhân Tông, Q Hai Bà Trưng 24/24",
      "11 Xuân Diệu, P Quảng Bá, Q Tây Hồ  Nội bộ",
      "32 Cát Linh, P Cát Linh, Q Đống Đa  Nội bộ",
      "1A Nghi Tàm, P Quảng An, Q Tây Hồ Nội bộ",
      "34B Trần Phú, P Điện Biên, Q Ba Đình  24/24",
      "126 Tam Trinh, Yên Sở, Q Hoàng Mai  8h-22h",
      "Đường Phạm Văn Đồng, Xuân Đỉnh, Từ Liêm 8h-21h",
      "Đường Trần Thái Tông, P Mễ Trì, Q Cầu Giấy  24/24",
      "183 Hoàng Hoa Thám, P Ngọc Hà, Q Ba Đình  24/24",
      "195 Khâm Thiên, P Thổ Quan, Q Đống Đa 24/24",
      "55 Le Hong Phong  7h30-17h",
      "110 Cầu Gỗ, P Hàng Bạc, Q Hoàn Kiếm 24/24",
      "33 Chùa Láng, P Láng Thượng, Q Đống Đa  7h30-17h",
      "Số 7 Phan Đình Phùng, TT Phùng, H Đan Phượng  24/24",
      "285 Đội Cấn, P Liễu Giai, Q Ba Đình 24/24",
      "29B Hai Bà Trưng, Q Hoàn Kiếm 7h30-17h",
      "55 Hàng Bún, P Quán Thánh, Q Ba Đình  24/24",
      "172 Ngọc Khánh, P Giảng Võ, Q Ba Đình 24/24",
      "Số 31, Q.Lộ 3, Tòa nhà trung tâm 4 Bưu điện Sóc sơn 24/24",
      "152 Thụy Khuê, P Thụy Khuê, Q Tây Hồ  24/24",
      "8 Đường Trung Hòa, P Trung Hòa, Q Cầu Giấy  7h30-17h",
      "51 Xuân Diệu, P Quảng An, Q Tây Hồ  24/24",
      "Số 18 Láng Hạ - Ba Đình 24/24",
      "6/200 Nguyễn Sơn Bồ Đề Long Biên HN 24/24",
      "102 Trường Chinh, P Phương Mai, Đống Đa 24/24",
      "200 Nguyễn Sơn, P Bồ Đề, Q Long Biên  24/24",
      "31-33 Ngô Quyền, P Hàng Bài, Q Hoàn Kiếm  24/24",
      "31-33 Ngô Quyền, P Hàng Bài, Q Hoàn Kiếm  7h30-17h",
      "12B Tổ 90, P Ô Chợ Dừa, Q Đống Đa 24/24",
      "1 Quang Trung, P Quang Trung, Q Hoàn Kiếm 24/24",
      "xã Tân Dân Sóc Sơn Hà Nội 24/24",
      "Số nhà 51 đường Quốc Lộ 3, tổ 12, thị trấn Sóc Sơn, huyện Sóc Sơn 24/24",
      "Xã Tiên Dược Sóc Sơn Hà Nội 24/24",
      "683 đường Lạc Long Quân, P Phú Thượng, Q Tây Hồ 6h-22h",
      "Số 903 Đ 3/2,Phú Xá,Thái Nguyên 24/24",
      "Nguyễn Văn Huyên, P Nghĩa Đô, Q Cầu Giấy  24/24",
      "129 Nguyễn Phong Sắc, P Nghĩa Tân, Q Cầu Giấy 24/24",
      "CT1 KĐT Mỗ Lao Hà Đông  24/24",
      "16 Phạm Hùng, P Mai Dịch, Q Cầu Giấy  24/24",
      "56 Vũ Trọng Phụng, Thanh Xuân 24/24",
      "Km12,QL32,Phúc Điền 24/24",
      "nhà A1 Nguyễn Cơ Thạch, Mỹ Đình, H Từ Liêm 7h-22h",
      "39 Xã Đàn, P Kim Liên, Q Đống Đa  7h-22h",
      "331B Phố Vọng, P Đồng Tâm, Q Hai Bà Trưng 7h-19h",
      "Tòa nhà Indochina Plaza Hà Nội  1 239 Xuân Thủy, Cầu Giấy 9-22h",
      "15 Phạm Hùng, P Dịch Vọng Hậu 24/24",
      "98 Hoàng Quốc Việt, P Nghĩa Đô, Q Cầu Giấy  7h-20h",
      "Mỹ Đình, Mễ Trì, H Từ Liêm  9h-20h",
      "Số 222 Trần Duy Hưng, Cầu Giấy  7h30-21h",
      "Số 2 Duy Tân, Cầu Giấy  24/24",
      "Tầng 1 C4 Giảng Võ, Q Ba Đình 24/24",
      "30 - 32 Láng Hạ, P Láng Hạ, Q Đống Đa 24/24",
      "HH4 tòa nhà Sông Đà, đường Phạm Hùng, H Từ Liêm 24/24",
      "116 Thái Hà, Đống Đa, Hà Nội  7h00-22h",
      "A4 khu Đấu Giá, đường Tố Hữu, Vạn Phúc, Hà Đông  7h30-22h",
      "Nhà 18T2 KĐT Trung Hòa - Nhân Chính, Lê Văn Lương, Q Thanh Xuân 24/24",
      "39 Vạn Phúc, P Kim Mã, Q Ba Đình  7h30-22h",
      "Siêu thị Mê Linh Plaza, Mê Linh 8h-22h",
      "Ô 4.1 CC Hoàng Đạo Thúy, P Nhân Chính, Q Thanh Xuân  24/24",
      "54 Liễu Giai, Q Ba Đình 7h30-22h",
      "KM10, đường Nguyễn Trãi, Phường Mỗ Lao, Hà Đông 8h-22h",
      "Số 609, Trương Định, Hoàng Mai  8h00-22h00",
      "Số 75 Phương Mai, Đống Đa 24/24",
      "BT8, nhà số 44, KĐT Văn Quán, Hà Đông 24/24",
      "Số 448-450 Nguyễn Trãi, Thanh Xuân, Hà Nội"
    ]


    100.times {|i|
      r = Restaurant.new(
        name: "Restaurant" + Faker::Name.name,
        address: ADDRESSES.sample,
      )
      r.save
    }

  end
end
